### ISSUE TITLE
Manual Deployment guide assumes usage of Elastic IP, but does not describe how to create it

### ISSUE THREAD

**Issue by slangenbach** [Netflix/metaflow-docs#5]
First of all, thank for creating such an elaborate documentation for Metaflow in general and for manual deployment specifically 👍🏻. I assume it can be tedious to keep it up to date, but it really helps users who can not use the Cloud Formation template for various reasons (such as myself).

While reading through the [manual deployment](https://github.com/Netflix/metaflow-docs/blob/metaflow-admin/aws-deployment-guide/deployment-guide/manual-deployment.md) guide within the admin docs section, I noticed that you refer to using an existing **Elastic IP** (Compute > Create VPC > 1. Run VPC Wizard > Step 4) , but do **not** mention how to create it in the first place:  
> For Elastic IP Allocation ID, choose the ID of the Elastic IP address that you created earlier.

While readers may figure out how to do so, it would be great if it was mentioned in the guide directly.

**Comment by savingoyal** [comment]
@slangenbach Thanks for pointing out the gap. I have updated the doc - https://admin-docs.metaflow.org/metaflow-on-aws/deployment-guide/manual-deployment#create-a-vpc
