### ISSUE TITLE
Link to configuring Metaflow in AWS CloudFormation Deployment guide is broken

### ISSUE THREAD

**Issue by slangenbach** [Netflix/metaflow-docs#7]
The link in the very bottom paragraph of the [AWS CloudFormation Deployment guide](https://admin-docs.metaflow.org/metaflow-on-aws/deployment-guide/aws-cloudformation-deployment) should link to https://admin-docs.metaflow.org/overview/configuring-metaflow, but actually links to https://admin-docs.metaflow.org/metaflow-on-aws/deployment-guide#configuring-metaflow

> Once you have followed all these steps, you can configure your metaflow installation using the outputs from the CloudFormation stack.

**Comment by savingoyal** [comment]
I have made the fix. Thanks for letting us know!
